AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates a Bedrock Cost Apportionment Proxy.

Parameters:
  pStageName:
    Type: String
    Description: Stage name for the API Gateway
    Default: v1
  pCloudWatchCustomMetricNamespace:
    Type: String
    Description: CloudWatch Custom Metric Namespace
    Default: BedrockCostApportionment

Resources:
  BedrockProxyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref pStageName
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionArn: !GetAtt LambdaAuthorizerFunction.Arn
      EndpointConfiguration:
        Type: REGIONAL

  LambdaAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      CodeUri: functions/lambda_authorizer
      Handler: app.lambda_handler
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          API_KEY_TABLE: !Ref ApiKeyTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ApiKeyTable

  BedrockProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      CodeUri: functions/bedrock_proxy
      Handler: app.lambda_handler
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          CLOUDWATCH_CUSTOM_METRIC_NAMESPACE: !Ref pCloudWatchCustomMetricNamespace
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: "*"
              Condition:
                StringEquals:
                  "cloudwatch:namespace": !Ref pCloudWatchCustomMetricNamespace
      Events:
        ProxyApi:
          Type: Api
          Properties:
            RestApiId: !Ref BedrockProxyApi
            Path: /invoke-model
            Method: POST

  ApiKeyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ApiKey
        Type: String

Outputs:
  BedrockProxyApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${BedrockProxyApi}.execute-api.${AWS::Region}.amazonaws.com/${pStageName}/invoke-model"
